language: c
before_script: cd _mirage
script: bash -ex travis.sh
env:
  matrix:
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0 MIRAGE_BACKEND=xen DEPLOY=1
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0 MIRAGE_BACKEND=unix
  global:
  - secure: Om1BdsBTIqqhoMN5KQvDzClaieKoNMWsvVWcW6oRdNsFaaFcsN66ASfSfbIZm6tOqAnulUK1xtf/07FL2hexJw9YNwQiGE0ih4z8NYuVuB6aF7VTMz0Ps/EFPmdc0X5Lx9LpYi0TmphzBDMoGmaAaGRZkvPexdVup0ml6GJ47i8=
  - secure: OZBJ52oFZS6U+97JitwFU7x1mWJLEh9h8f+orhARZbQetEDBQfL1xU6e9YzrhOUOEXKFSb2O+Iiyh1Jw/fEzQeNfszztn783Npor0+/VKolk7PYHwgbWTtMCKCJ1ot6qhSHviLWu8qMKv/bcyJjNkHE+w992Z2g4Q03MixMntG8=
  - secure: QKirHJBXSXnwu0md7FLBNsDraCIPmxaqmoqGGpZ778HLSbp0UqaaQ2OFc27Ms8QJMpOtl7J04P+fE1iXZ+dw3Kr0eGpU5cypqbLo1+hJpxoYutegzMzL4khSnbO5GewacOWum0RYv1zX58pFjQi8JjDfYR63+d0fh51seYuZWhg=
  - secure: NAAsUmKSotz7ZAHUWf+UzB6It+wq8cXpkIWIunbvVM9bJUGR1j758QF6a0zHT2QNOZedX55jy8pCnKzvJnH0jVYZ7Ll2yGNrEqXv873VKIpmrMele4fPdGF9aODhjkDGm1iPxHI7UQHfovzYuyXTJHuFQXcqLSOStrCrXFKvPTs=
  - secure: UPu/QOljYHHZbqDZQhgBZDEIClfhPgoRwN8gkVUpPK2DIACHutDmSbGBlkUZ+Y4pO+A0NkGTFupKgil6C4jyA8K8i1+Kpqm+b9AIpCBE8U21+GLVYWMO8KZApbLSCunXq50W5YWOp7D1I2u8BJ5/tV6C2OotVzq6XU5KRnZClKg=
  - secure: Tm6LAJHYsxxaDFpylUtMycK9kS6T3R9EQO1lrDM0/oBIS7CgO56LosM2EvEJKoIn00PPjd8QXKNVa3UzUcWtdLOT5bNbqxjFGoOHEQzb00VE/ztUipaY/ieMhKt+m7p4HNBwv4CLLVUNVS0spHXHTRHOTvEdnWAST9bi5gVrQRY=
  - secure: Yjwl6IO4VNtFd+EEVMw7euzcIa9+hkoFWKEEq1CQtlCAEt54j4Li0us2PEGbcVlSRXGkRUyk1dRYMpBVTDSiqJrExGESdBJJLcmdi5Za2mXJENR4DpE/kiweVXOsfEy1Q4vDVmGEnFjbj2B122syN7sadZZQdq4/gu5Yj54WJLo=
  - secure: TN+poi9a0xi7rtbrWXKCgktlKSWBexBOnFtSFVjGV2IWtfXrg8VN2ekuJf/Udr5hPmRDDgR7LBll0erHfXj0EjN4PSLuzirK6S7ThFvFA6rZqaVRWyxaAYuCH5KctWQWTyeRx3U0puA+3oWc94/L0QVRxkDU2Blr7TkKSC6kDZU=
  - secure: PIdk9CxzQTEdK7DN6Mjh6VoBQcLh+SCfABXH9pxnAAKai5QPF+d2lMANaip/+SPdXE1WKNoGfme5W7OqqxIOhRn/UhQW9rzagMDFv2XPECPuCMNSo22AKfB91aRf83IpYYeo5KlrP+ElcJ1KP/bp/OQgZj4l3AF0i4aFnpY8goQ=
  - secure: PI0nndbFjXQnK9a9BCgT/XiT1U5i78Dv+P1r0lv7yIqa1+a2CSsKK1huRMGUDXVRRhhB72H5wzz/OE5h9UldCK2m0vgU2813b69dwb6r94a9MDPIrN0uyA5tiyrHsbk2nH6vEHs6j/0r5NlVb07icLBWIyp5m4uph9riMlz7YFE=
  - secure: QqbGYvAF/jn5Nq4bxF5VtWEydUxH+mYY6PAKDaLi+X41suaTb+5xH1y6PlpxOia6+u92XnASti9hMGgVy/ZiWFjTzRfzCMSWQ94xVoHRF7JV9HuRI7FfRL448cosFvuYQUn5X5VDr8R0uS1cf5ikm5YLrI1toSPyJbOcyOoIWbA=
  - secure: FB88ItHkTe2cOCQMV4dJXpPnzmoW6boG9JJDhvRPkFuIwEKdAWS1R+gjOuKjqF1du5J9qYrn4P9X5JDi/kzUbSNG/M35TDzR49yaqUZH6uClzMqdsXeNeYZQZreh4QF6xXkgfPINnDjU1erK0CugpBiJc/S73IlIdGhJO60eU5Y=
  - secure: XYLG/31PvleCs+wBrDPcjPwljrYBxOWPWKrdY1b05sM1YaGrpEF0IWo4ztIX1CKL62TC9fkpdBBrN4isrQOJ18+fewd8xhob/gVRk/j/1JGNJrieujgD6fwdCxXQM1Wk61G1kVqYXgm9IvvVBKw81VLcga5cmRBFKxkCFRL7hR8=
